### ISSUE TITLE
changing timezone, root pass, hostname still busted

### ISSUE THREAD

**Issue by boneskull** [OnionIoT/Onion-Console#10]
err in console:

```[onion-settings-general::_createEventHandler]: listener method `setupWifi` not defined
12onion-session-provider.html:107 Alive```

**Comment by boneskull** [comment]
I'm not familiar with polymer, but if I had to make a WAG:

```html
<button id="wifi-config-button" type="button" class="btn btn-success btn-block" on-tap="saveSettings">Save Settings</button>
```

`id="wifi-config-button"` is confusing whatever event bindings are happening.

**Comment by boneskull** [comment]
if I were to send a PR to fix this, how would I set up a dev environment?

**Comment by Bokenator** [comment]
@boneskull It seems to work on my end. Can you tell me which browser you are using it on? I will try to debug it.

**Comment by greenbreakfast** [comment]
@boneskull can you try upgrading to the latest Omega firmware and trying again?

**Comment by boneskull** [comment]
will try.

**Comment by boneskull** [comment]
I can confirm this is now working.  thanks
