### ISSUE TITLE
Onion Launch Icon image src 404s

### ISSUE THREAD

**Issue by bikegriffith** [OnionIoT/Onion-Console#23]
Looks like it's pointing to `/apps/onion-terminal/icon.png` instead of `/console/apps/onion-terminal/icon.png` like the sidebar is.

![image](https://cloud.githubusercontent.com/assets/167782/21572893/7b4bb688-ceac-11e6-82d3-965e4534be59.png)

**Comment by greenbreakfast** [comment]
can you please try using opkg to remove `onion-console-base` and then installing it again?

**Comment by bikegriffith** [comment]
I would normally, but an attempted firmware update last night seems to have bricked my device.

**Comment by bikegriffith** [comment]
(deleted last comment)

Looks like the latest firmware has the fix

**Comment by greenbreakfast** [comment]
Yep, we had fixed it on the omega2 branch which has now been merged into master! https://github.com/OnionIoT/Onion-Console/blob/master/www/apps/onion-launcher/onion-launcher.html#L266
