### ISSUE TITLE
Onion Omega2+ keeps bumping me back to the login screen. 

### ISSUE THREAD

**Issue by benpete22** [OnionIoT/Onion-Console#25]
It works for a few seconds and then back to the login screen

**Comment by trickeydan** [comment]
I would like to add that my Omega 2+ also has this issue.

**Comment by greenbreakfast** [comment]
can you please try using opkg to remove onion-console-base and then installing it again?

**Comment by benpete22** [comment]
I was still able to ssh into it so I tried that. Opkg would not let me remove onion-console-base, so I ran oupgrade and it downloaded 0.1.7
After doing the initial setup screen again it appears to now be working.

**Comment by benpete22** [comment]
This issue was resolved with a firmware update.
