### ISSUE TITLE
Reboot/Shutdown not working

### ISSUE THREAD

**Issue by WereCatf** [OnionIoT/Onion-Console#26]
With the bottom-left corner the menu with Restart, Shutdown and Logout menu-entries, they all just log you out. Restart or shutdown ain't working. Tested with several firmware-versions, including 0.1.7 b140

Tested using Edge, Firefox and Chrome on Windows 10.

**Comment by hoipolloimike** [comment]
I have also found that if I ssh in or use the console to reboot it won't reboot. It shuts down but doesn't come back on. This also happened during firmware upgrade. I had to manually switch it off and switch it back on. Firmware 0.1.7 (b139).

**Comment by tim427** [comment]
Confirmed on 0.1.7 (b139)

**Comment by ElanMorin** [comment]
Same on 0.1.7. (b139 & b140)

**Comment by rali717** [comment]
"poweroff" does not work. It never does before really right.
But with the   0.1.8 b145  version  it makes a reboot, 
not a shutdown.
