### ISSUE TITLE
Changing password doesn't work

### ISSUE THREAD

**Issue by WereCatf** [OnionIoT/Onion-Console#27]
Console claims password was updated, but no change actually happens. Password stays the same as it was.

Tested using Firefox, Edge and Chrome under Windows 10.

**Comment by torwag** [comment]
I can confirm this for a omega2+. Console claims the change but it was not put into effect. Changing the password via ssh and passwd did work

**Comment by kdupreez** [comment]
Same here.. default password stays in effect.. you cant change it..

**Comment by tim427** [comment]
Confirmed on 0.1.7 (b139)

**Comment by algern0n** [comment]
I got the same issue on Omega2+, 0.1.7 (b139)

**Comment by kdupreez** [comment]
No word from Onion??  They are very quiet and not much seems to work..  

I bought 3 x Omega2+ and they are pretty useless since the cloud doesnt work and you cant turn off AP pass through mode and you cant change default passwords.. 

meaning you have a rogue wireless access point on your network with default admin password you cant change...

**Comment by WereCatf** [comment]
@kdupreez You can change the password by logging in from serial or SSH and calling `passwd`

**Comment by kdupreez** [comment]
These will remain in the box until they fix the issues..  Its terrible to release something with such broken software..  they should rather have waited a couple months and released something that works.

**Comment by ElanMorin** [comment]
Same on 0.1.7. (b139 & b140)

**Comment by symonty** [comment]
Agree same issue just updated to lattest version, will use ssh.

**Comment by geurti** [comment]
Console send : "{"code":127,"stderr":"\/usr\/sbin\/change-password: line 86: chpasswd: not found\n"}]}"

replace by passwd works : in change-password script: 
echo -e "$2\n$3" | (passwd $1)

**Comment by ageeweb** [comment]
same issue
version 0.1.9 (b149)

**Comment by greenbreakfast** [comment]
fixed! https://github.com/OnionIoT/Onion-Console/pull/52
