### ISSUE TITLE
Change root password does not work 

### ISSUE THREAD

**Issue by mh1412** [OnionIoT/Onion-Console#3]
* Under Settings > General Settings 
* Type in new root password, retype new root password to verify
* click Save Settings 
* try log out and login to Omega
* new root password does not take in effect

**Comment by Bokenator** [comment]
Bug fixed in 0.0.4

**Comment by bermudez** [comment]
I confirm that 0.0.4 firmware fixed it.  However, just a few notes on which browser worked for me and which didn't:
Chromium -- buggy; didn't work in changing the password
Safari -- console doesn't work at all
Firefox (on Ubuntu 14.04LTS) -- worked!
