### ISSUE TITLE
Ctrl+C and Ctrl+V does not work on terminal app

### ISSUE THREAD

**Issue by yeyeto2788** [OnionIoT/Onion-Console#32]
Hello guys! 

Just to mention that Ctrl+C and Ctrl+V does not work as keyboard commands, not even as normal terminal (Ctrl+Shift+C and Ctrl+Shift+V).

The only way to accomplish this is by going into Browser's Navigation Bar>Edit>Paste.

Regards.

**Comment by ElanMorin** [comment]
Same on 0.1.7. (b139 & b140)

**Comment by Tauby** [comment]
It seems to be a systematic issue: Same problem on the Mac with Command-C and Command-V. Pasting from the menu bar works.

Having fun, though!

**Comment by donde1** [comment]
Also up/down arrow keys don't remember

**Comment by yeyeto2788** [comment]
@Bokenator, @ratatatatat, @theclementho any updates here?

Regards.

**Comment by yeyeto2788** [comment]
Closing issue since it seems that this won't be fixed.

Regards.
