### ISSUE TITLE
fast-gpio commands produce segmentation fault

### ISSUE THREAD

**Issue by mploof** [OnionIoT/Onion-Console#39]
```
root@Omega-AAFD:~# fast-gpio set-output 7
Segmentation Fault
root@Omega-AAFD:~# fast-gpio get-output 6
Segmentation Fault
root@Omega-AAFD:~# fast-gpio set-input 7
Segmentation Fault
```

**Comment by dawru** [comment]
try
fast-gpio set <gpio> <value: 0 or 1>
fast-gpio set 0 1

**Comment by greenbreakfast** [comment]
[Update to firmware b160](https://docs.onion.io/omega2-docs/using-the-omega-updating.html), this has been resolved: https://docs.onion.io/omega2-docs/known-firmware-issues.html#known-firmware-issues
