### ISSUE TITLE
Kernel/Repo mismatch

### ISSUE THREAD

**Issue by mh1412** [OnionIoT/Onion-Console#5]
When installing some packages with `opkg install` error will occur with kernel version mismatch.

![screen shot 2015-11-06 at 11 20 49 am](https://cloud.githubusercontent.com/assets/1589034/11002046/772b2e32-8478-11e5-86bb-97d62bf4eb48.png)

**Comment by borromeotlhs** [comment]
you can try to force it. Have you attempted that?

**Comment by develroo** [comment]
That won't work because it need the tun kernel module and that is compiled specifically again the kernel in the repos.

**Comment by thk4711** [comment]
Can you PLEASE update the OpenWrt Package repo to the same version as your image. It should be very easy. Everything is created when you compile OpenWrt. You just have to copy that to your web server as well.

**Comment by greenbreakfast** [comment]
As of version 0.1.7, this is fixed.
Please see the docs site for details: https://docs.onion.io/omega2-docs/software-using-opkg.html#onion-package-repo
