### ISSUE TITLE
Status widget shows uptime excluding days

### ISSUE THREAD

**Issue by Agathia** [OnionIoT/Onion-Console#8]
Status widget shows uptime as hh:mm:ss but excludes days

**Comment by greenbreakfast** [comment]
Hi, this is fixed in the newer versions of the console.
Can you please upgrade to the latest Omega firmware and check again?

**Comment by Agathia** [comment]
I was on 0.06 (b266), upgraded to 0.0.7 (b281). Interestingly, when I checked on 0.0.6, it was showing uptime of 40+ days (plus hh:mm:ss). Following upgrade, it just shows hh:mm:ss but I suspect that the reflash reset uptime to 0, so it would be technically correct. Will check again tomorrow and if days are shown will close the issue. Thanks.

**Comment by greenbreakfast** [comment]
Yep, upgrading the firmware will cause the Omega to reboot so the uptime reset makes sense

**Comment by Agathia** [comment]
Sorry for the delay. Can confirm uptime shows days. Thanks.
